/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtsRouteImport } from './routes/ots'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BoxesIndexRouteImport } from './routes/boxes/index'
import { Route as BoxesBoxIdRouteImport } from './routes/boxes/$boxId'
import { Route as PokemonIndexRouteImport } from './routes/pokemon/index'
import { Route as PokemonPokemonIdRouteImport } from './routes/pokemon/$pokemonId'
import { Route as PokemonNewRouteImport } from './routes/pokemon/new'
import { Route as PokemonPokemonIdEditRouteImport } from './routes/pokemon/$pokemonId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtsRoute = OtsRouteImport.update({
  id: '/ots',
  path: '/ots',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesIndexRoute = BoxesIndexRouteImport.update({
  id: '/boxes/',
  path: '/boxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBoxIdRoute = BoxesBoxIdRouteImport.update({
  id: '/boxes/$boxId',
  path: '/boxes/$boxId',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonIdRoute = PokemonPokemonIdRouteImport.update({
  id: '/pokemon/$pokemonId',
  path: '/pokemon/$pokemonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonNewRoute = PokemonNewRouteImport.update({
  id: '/pokemon/new',
  path: '/pokemon/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonPokemonIdEditRoute = PokemonPokemonIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PokemonPokemonIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ots': typeof OtsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRouteWithChildren
  '/pokemon/new': typeof PokemonNewRoute
  '/boxes/': typeof BoxesIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/pokemon/$pokemonId/edit': typeof PokemonPokemonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ots': typeof OtsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRouteWithChildren
  '/pokemon/new': typeof PokemonNewRoute
  '/boxes': typeof BoxesIndexRoute
  '/pokemon': typeof PokemonIndexRoute
  '/pokemon/$pokemonId/edit': typeof PokemonPokemonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ots': typeof OtsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/pokemon/$pokemonId': typeof PokemonPokemonIdRouteWithChildren
  '/pokemon/new': typeof PokemonNewRoute
  '/boxes/': typeof BoxesIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/pokemon/$pokemonId/edit': typeof PokemonPokemonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ots'
    | '/register'
    | '/settings'
    | '/boxes/$boxId'
    | '/pokemon/$pokemonId'
    | '/pokemon/new'
    | '/boxes/'
    | '/pokemon/'
    | '/pokemon/$pokemonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ots'
    | '/register'
    | '/settings'
    | '/boxes/$boxId'
    | '/pokemon/$pokemonId'
    | '/pokemon/new'
    | '/boxes'
    | '/pokemon'
    | '/pokemon/$pokemonId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ots'
    | '/register'
    | '/settings'
    | '/boxes/$boxId'
    | '/pokemon/$pokemonId'
    | '/pokemon/new'
    | '/boxes/'
    | '/pokemon/'
    | '/pokemon/$pokemonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OtsRoute: typeof OtsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  BoxesBoxIdRoute: typeof BoxesBoxIdRoute
  PokemonPokemonIdRoute: typeof PokemonPokemonIdRouteWithChildren
  PokemonNewRoute: typeof PokemonNewRoute
  BoxesIndexRoute: typeof BoxesIndexRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ots': {
      id: '/ots'
      path: '/ots'
      fullPath: '/ots'
      preLoaderRoute: typeof OtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/': {
      id: '/boxes/'
      path: '/boxes'
      fullPath: '/boxes/'
      preLoaderRoute: typeof BoxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$boxId': {
      id: '/boxes/$boxId'
      path: '/boxes/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof BoxesBoxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemonId': {
      id: '/pokemon/$pokemonId'
      path: '/pokemon/$pokemonId'
      fullPath: '/pokemon/$pokemonId'
      preLoaderRoute: typeof PokemonPokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/new': {
      id: '/pokemon/new'
      path: '/pokemon/new'
      fullPath: '/pokemon/new'
      preLoaderRoute: typeof PokemonNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$pokemonId/edit': {
      id: '/pokemon/$pokemonId/edit'
      path: '/edit'
      fullPath: '/pokemon/$pokemonId/edit'
      preLoaderRoute: typeof PokemonPokemonIdEditRouteImport
      parentRoute: typeof PokemonPokemonIdRoute
    }
  }
}

interface PokemonPokemonIdRouteChildren {
  PokemonPokemonIdEditRoute: typeof PokemonPokemonIdEditRoute
}

const PokemonPokemonIdRouteChildren: PokemonPokemonIdRouteChildren = {
  PokemonPokemonIdEditRoute: PokemonPokemonIdEditRoute,
}

const PokemonPokemonIdRouteWithChildren =
  PokemonPokemonIdRoute._addFileChildren(PokemonPokemonIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OtsRoute: OtsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  BoxesBoxIdRoute: BoxesBoxIdRoute,
  PokemonPokemonIdRoute: PokemonPokemonIdRouteWithChildren,
  PokemonNewRoute: PokemonNewRoute,
  BoxesIndexRoute: BoxesIndexRoute,
  PokemonIndexRoute: PokemonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
